#!/bin/bash

. $(dirname $0)/.env.vid
shopt -s extglob

matchmsk() {
	[[ ${1:0:1} == '?' ]] && mdt=0 || mdt=1

	for tid in ${!lmd[@]}; do
		# Optional mask. May match on multiple tracks.
		if [[ $mdt == 0 && ! ${lmd[$tid]##${1:1}} ]]; then
			unset lmd[$tid]
		fi

		# Mandatory mask. Must match on some unique track.
		if [[ $mdt == 1 && ! ${lmd[$tid]##${1%%'#'*}} ]]; then
			# Record track ID.
			if [[ ! ${1%%*'#'*t*} ]]; then
				prm[${1:0:1}]=$tid
			fi

			# Record language.
			if [[ ! ${1%%*'#'*l*} ]]; then
				# On specified track, or config entry default.
				prm[l]=${stream_tags_language[$tid]}

				[[ ! ${prm[l]} || ${prm[l]} == und ]] && prm[l]=$ldf
			fi

			# Matched. Disable track of further check.
			unset lmd[$tid]

			return 0
		fi
	done

	return $mdt
}

match() {
	local lmd msk i

	for i in ${!gmd[@]}; do lmd[$i]=${gmd[$i]}; done
	for msk in $1; do if ! matchmsk $msk $2; then return 1; fi; done

	# Not all tracks matched. Try again.
	[[ ${!lmd[@]} ]] && return 2

	return 0
}

usage() {
        usageh "file" "Handle video file and register tracks to be processed."
        option "d" "Dry run. Just display (in log file) what would happen."
        exit 1
}

while getopts $(flg "d") opt; do
        case $opt in
        d)
		dry=1
                ;;
        esac
        casel $opt
done

shift $((OPTIND - 1))

exec &>> $LVID
exec 3< /tmp

[[ -z $1 ]] && log "No file specified. Skip." ERR && exit 1

# Silently ignore hidden files.
[[ ${1:0:1} == '.' ]] && exit 0

# Silently ignore unhandled files.
[[ -n ${1%%*@(.mkv|.avi|.mp4)} ]] && exit 0

# Exclusive lock on /tmp dir.
flock 3

log "Handling file: $1"

dir=all
for f in $DIRVID/.vid.kids.*; do 
	if [[ -f $f ]]; then
		log "Kids handler. Update settings."
		
		CFGRX="$CFGRXK"
		dir=kids

		$RM $f
		num=${f##*'.'}

		[[ $num -gt 1 ]] && $TOUCH $DIRVID/.vid.kids.$((num - 1))
	fi
done
for f in $DIRVID/.vid.mov.*; do
	if [[ -f $f ]]; then
		log "Mov handler. Just move, no wait."
		
		$MV "$DIRVID/$1" "$DIRVID/$dir/$1"
		[[ $? -ne 0 ]] && log "Unable to move. Abort." ERR && exit 1

		log "File moved."

		$RM $f
		num=${f##*'.'}

		[[ $num -gt 1 ]] && $TOUCH $DIRVID/.vid.mov.$((num - 1))
		exit 0
	fi
done

srcstreams "$DIRVID/$1"

# Sanitize.
for i in $(seq 0 $(($($FFPRB -show_entries format=nb_streams -of default=noprint_wrappers=1:nokey=1 "$DIRVID/$1") - 1))); do
	# Exclude explicit attachments.
	[[ ${stream_codec_type[$i]} == attachment ]] && continue

	# Exclude attached pics, seen as video streams.
	[[ ${stream_disposition_attached_pic[$i]} == 1 ]] && continue

	# Exclude some identified useless subs (e.g. SDH - Subtitles for the Deaf and Hard of hearing).
	[[ ${stream_codec_type[$i]} == subtitle ]] && if valmatch "${stream_tags_title[$i]}" sdh song songs chanson chansons; \
			then continue; fi

	# Exclude unhandled bitmap subs.
	if valmatch "${stream_codec_name[$i]}" pgssub dvdsub hdmv_pgs_subtitle; then continue; fi

	# Restore forced subtitles.
	[[ ${stream_codec_type[$i]} == subtitle ]] && if valmatch "${stream_tags_title[$i]}" force forced forcé forcés forces; \
			then stream_disposition_forced[$i]=1; fi

	# Language specified in title.
	if valmatch "${stream_tags_title[$i]}" anglais english;          then stream_tags_language[$i]=eng; fi
	if valmatch "${stream_tags_title[$i]}" français francais french; then stream_tags_language[$i]=fre; fi

	# Additional check on subtitles file size to set forced flag. Slow down process.
	[[ ${stream_codec_type[$i]} == subtitle ]] && if chkforced "$DIRVID/$1" $i "${stream_codec_name[$i]}"; \
			then stream_disposition_forced[$i]=1; fi

	gmd[$i]=${stream_codec_type[$i]:0:1}:${stream_tags_language[$i]}:${stream_disposition_default[$i]}:${stream_disposition_forced[$i]}
done

log "Media signature: $(for i in ${!gmd[@]}; do echo -n "$i=${gmd[$i]} "; done)"

while IFS='%' read -r cfg ldf; do
	[[ ! $cfg || ${cfg:0:1} == '#' ]] && continue

	declare -A prm=()
	if match "$cfg" $ldf; then
		log "Successful match with $cfg"
		log "Match gives: $(for i in ${!prm[@]}; do echo -n "$i=${prm[$i]} "; done)"
		
		$VQUEUE$(for i in ${!prm[@]}; do echo -n " -$i" ${prm[$i]}; done) -d $dir "$1"
		exit
	fi
done < $CFGRX

log "Fail to match. Abort." ERR
exit 1
