#!/bin/bash

. $(dirname $0)/.env.vid

usage() {
	usageh "file" "Queue video file for processing."
	option "v tid" "Mandatory. Video track."
	option "a tid" "Mandatory. Audio track."
	option "s tid" "Subtitle track if any."
	option "l lang" "Audio language - mandatory."
	option "d dir" "Export directory. Defaults to 'all'".
	option "i" "List queue file and exit."
	exit 1
}

dir=all
while getopts $(flg "v:a:s:l:red:i") opt; do
	case $opt in
	v)
		vid=$OPTARG
		;;
	a)
		aid=$OPTARG
		;;
	s)
		sid=$OPTARG
		;;
	l)
		lng=$OPTARG
		;;
	d)
		dir=$OPTARG
		;;
	i)
		cat $FQUEUE ; exit
		;;
	esac
	casel $opt
done

[[ ! $vid ]] && error "missing video track"
[[ ! $aid ]] && error "missing audio track"
[[ ! $lng ]] && error "missing audio language"

[[ -d "$DIRVID/$dir" ]] || error "export directory does not exist"

shift $((OPTIND - 1))
(($# == 0)) && error "missing file name"

echo "$(basename "$1")"'!'$vid'!'$aid'!'$sid'!'$lng'!'$dir >> $FQUEUE
