#!/bin/bash

. $(dirname $0)/.env.vid

usage() {
	usageh "" "Reads queue file and processes remuxing files sequentially."
	exit 1
}

while getopts $(flg) opt; do
        casel $opt
done

exec &>> $LVID

log "Processing queue."
while IFS='!' read -r flo vid aid sid lng dir; do
	[[ -f "$DIRVID/$flo" ]] || continue
	log "File $flo found. Processing."

	$VPROC -v $vid -a $aid ${sid:+-s $sid} -l $lng -d $dir "$flo"
	[[ $? -ne 0 ]] && $EXEC $0 "$@"

	log "Finished processing file."
	$EXEC $0 "$@"
done < $FQUEUE

log "No new task queued. Purge."
$TRUNC -s 0 $FQUEUE

log "Finished processing queue."
